CREATE TABLE station(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL UNIQUE);

CREATE TABLE data(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	id_station INTEGER,
	time_measure TEXT,
	temperature REAL,
	Po	REAL,
	P   REAL,
	Pa  REAL,
	U   INTEGER,
	DD	TEXT,
	Ff	INTEGER,
	ff10 INTEGER,
	ff3	INTEGER,
	N   TEXT,
	WW	TEXT,
	W1	TEXT,
	W2	TEXT,
	Tn	REAL,
	Tx  REAL,
	Cl	TEXT,
	Nh	TEXT,
	H	TEXT,
	Cm	TEXT,
	Ch	TEXT,
	W   REAL,
	Td	REAL,
	RRR	TEXT,
	tR  INTEGER,
	E   TEXT,
	Tg	TEXT,
	E2	TEXT,
	sss	TEXT,
	CONSTRAINT uc_data UNIQUE (id_station,time_measure),
	FOREIGN KEY(id_station) REFERENCES station(id)
);